### ISSUE TITLE
Entering Token does not do anything..

### ISSUE THREAD

**Issue by monckey100** [SebOuellette/Discord-LiveBot#15]
I have entered Tokens for 3 different bots and it does not proceed. I installed electron in administrator mode and ran npm install.

**Comment by SebOuellette** [comment]
Sorry about that! Yeah this is an issue atm. It will be a few days until I am able to work on it though, but don't worry! The fix is on it's way!

**Comment by SebOuellette** [comment]
Livebot is now functional in commit e64f299800fbd33337c06a9c0ae043432d5caa6d
