### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by yann674** [SebOuellette/Discord-LiveBot#16]
i cant connect with the bot token, when i try nothing happens

**Comment by SebOuellette** [comment]
I (thought I) fixed this issue 5 days ago, how recently did you download?

**Comment by yann674** [comment]
i have redowloaded today

**Comment by SebOuellette** [comment]
Okay. If I may, I'm going to ask you to do a few things
1. Run `npm install discord.js` in the main livebot folder
2. Open livebot, press ctrl+shift+i, click "Console", and tell me what errors appear

**Comment by yann674** [comment]
this error 
![Sans titre](https://user-images.githubusercontent.com/39313199/72906843-23b65600-3d33-11ea-875b-08737dd7ea09.png)

**Comment by SebOuellette** [comment]
Okay that's what I thought. `npm install discord.js` should fix this.

**Comment by yann674** [comment]
![Sans titre](https://user-images.githubusercontent.com/39313199/72907425-1ea5d680-3d34-11ea-8353-8efdaf9a55b2.png)

**Comment by SebOuellette** [comment]
Right okay. I will have to update livebot so this doesn't happen anymore. For now, please try one more thing.
`npm update -D`

**Comment by yann674** [comment]
dont work
![image](https://user-images.githubusercontent.com/39313199/72908122-53fef400-3d35-11ea-9be8-6737b3e3c484.png)

**Comment by SebOuellette** [comment]
Hi
I believe this issue can be resolved by just reinstalling discord.js
`npm uninstall discord.js`
`npm install discord.js`

I'll be updating package.json later tonight so that this is automatic.

**Comment by SebOuellette** [comment]
Should be fixed in 4291a07a363dd7c45a64e84856a85746dcd2ef16 . Just download package.json, replace it, and then run `npm install`. Or you can just download the entire thing and replace it.

**Comment by DiamondDemon669** [comment]
ok
