### ISSUE TITLE
Shows the server but doesn’t load the server

### ISSUE THREAD

**Issue by Parkeriscoo** [SebOuellette/Discord-LiveBot#17]

**Comment by SebOuellette** [comment]
HI, I'm aware of this issue and I am currently working on a fix. I'll get back to you when it's resolved

**Comment by SebOuellette** [comment]
Fixed in e5499521231af0e37743c5152040532af6ce800f

**Comment by Parkeriscoo** [comment]
Can you please delete this issue.
