### ISSUE TITLE
This happens

### ISSUE THREAD

**Issue by aspirinety** [SebOuellette/Discord-LiveBot#19]
when i start up the app after installing the app
![image](https://user-images.githubusercontent.com/60390246/73264082-21a13b00-41fc-11ea-85fc-da2b01dafed1.png)
this blank screen shows up and i cant do anything

**Comment by SebOuellette** [comment]
Please install the latest version, and follow installation steps in the readme

**Comment by aspirinety** [comment]
i did all the steps but it still dosent work

**Comment by aspirinety** [comment]
the latest version work

**Comment by SebOuellette** [comment]
Nice, and thank you :) If you want to have an easier install, you can switch to the `executable` branch and install that, then just open the exe file (if you're on windows)
