### ISSUE TITLE
DM Support

### ISSUE THREAD

**Issue by SylveonBottle** [SebOuellette/Discord-LiveBot#20]
Please leave this issue open as a form of "status" for this feature, unless the feature is not planned for Livebot - i.e. don't close it just because it's already planned.

It'd be amazing if we could have DM support for bots. My intentions are to move over from a user account to a bot account, it's necessary to be able to interact with DM's.

Features for full DM support include:
-Notification upon receiving a DM (with the ability to disable this option globally or per-user) (potentially show notifications for DM's received while offline?)
-The ability to view said DM
~~-The ability to view a list of open DM's (similar to discord's "Direct Messages" tab, which shows all of your dm's)~~
-The ability to create a DM via inputting a discord discriminator 
-The ability open/create a DM with a user via context menu in a server (rightclick user > "Message")
-Retain message history over app instances (view the message history for DM's)

**Comment by marens101** [comment]
I'm not sure if some of these features are even possible, Discord removed the ability for a bot to see any DMs it has awhile back, we now have to rely on the messageRecieved event.

**Comment by SylveonBottle** [comment]
> Discord removed the ability for a bot to see any DMs it has a while back, we now have to rely on the messageRecieved event.
Oh wait, seriously? Wooowww, big rip.. 
Maybe we could log previous messages and save them to a file.. but, like, at that point.. Big rip.

**Comment by SebOuellette** [comment]
Because bots cannot see dms, support for dms will likely not be considered. Join the discord link on the readme page for faster responses or to place new suggestions.
