### ISSUE TITLE
Support for selfbot plugins

### ISSUE THREAD

**Issue by SylveonBottle** [SebOuellette/Discord-LiveBot#23]
Allow users to write plugins for Discord-LiveBot in order to run selfbot code with bot accounts. 

Since bot accounts are more feature-rich than user accounts, when it comes to the API, we could bulk delete messages and more, as well as run self-bot code on the accounts without violating discord TOS.

I do not plan on this being implemented until LiveBot is fully functional in all other aspects, I'm simply noting it down because it would be awesome to have a repository of user-created plugins that you can toggle on in Discord-LiveBot in the future. Think BetterDiscord plugins, but for LiveBot, whereas they are not against discord TOS.

**Comment by SylveonBottle** [comment]
Examples of plugins for the future:
-Bulk delete messages
-Auto moderation
-More/Custom macros
-Instant OAuth2 generation for into the chat for server administrators
-Ability to see deleted/edited messages (as this would not be against discord TOS if you're using a bot account, from my knowledge? There are _plenty_ of bots and servers that use said bots that log deleted/edited messages already. This would be no different, but in client form)
-Pretty much anything and everything you can do using BetterDiscord.

**Comment by SebOuellette** [comment]
Hm I do like this idea, however this will be an extremely late addition

**Comment by PhoenixOnARoof** [comment]
> Hm I do like this idea, however this will be an extremely late addition
As a bot dev I can't help but think: "All those things can pretty easily just be done on a bot"...

**Comment by SebOuellette** [comment]
Yeah, but providing easy access to do it via livebot would be nice, since you don't have access to any normal bot commands for the bot you're in.

**Comment by SylveonBottle** [comment]
That's pretty much the thing. Since you're using a bot account, it's an easy to guess that the reason is because you want to do bot-related stuff. You can't really do bot-related stuff using an external bot - or, rather, one would assume that the program that lets you *be* the bot also lets you *do* the bot stuff. 

Being able to impliment self-bot code/plugins would be pretty amazing. In fact, it's probably the only reason anyone would ever want to use Discord-LiveBot for bot accounts - being able to use selfbots without going against the discord TOS for using them on user accounts.

**Comment by SebOuellette** [comment]
I honestly haven't even thought about that... I'm probably going to put that higher on my list of to do. I'm even excited about that haha

**Comment by SebOuellette** [comment]
This feature has been added! There is a scripts folder with a template for your own so that you know how to do it. Feel free to join the discord server on the readme to give your feedback!
