### ISSUE TITLE
Incorrect font for Cyrillic text

### ISSUE THREAD

**Issue by Kolonsky** [SebOuellette/Discord-LiveBot#25]
![изображение](https://user-images.githubusercontent.com/50499916/74083640-a9e2d400-4a77-11ea-9db1-a31f4cf1c69e.png)
There's no Cyrillic symbols in current font. Maybe use Arial or similar if current font does not contain the necessary characters?

**Comment by SebOuellette** [comment]
Oh I didn't even thing about this! I just fixed it in 349bb4fbc9c5efffaaea9697716037022cb8d8b9 :)
