### ISSUE TITLE
Links parsing

### ISSUE THREAD

**Issue by Kolonsky** [SebOuellette/Discord-LiveBot#27]
![изображение](https://user-images.githubusercontent.com/50499916/74133654-17b70900-4bfa-11ea-8356-9571ddd2dbe4.png)
Wrong links parsing.

**Comment by SebOuellette** [comment]
This is pretty weird.. I'm unable to test on the application at the moment, however the regex works in the online tester, the exact line used to parse links I put into a javascript sandbox and it works flawlessly. I'll make sure to get this fixed by tonight, my apologies for the delay.

**Comment by SebOuellette** [comment]
Fixed in d601df97f26ddbea044650681a7251f1bf52dfb7
