### ISSUE TITLE
i cant type anything on. mac

### ISSUE THREAD

**Issue by roboaaron1** [SebOuellette/Discord-LiveBot#28]
i go into liscence with terminal on mac, but it doesn't let me type anything. help

**Comment by SebOuellette** [comment]
Sorry just to clarify; you can't type anything in the license file?

**Comment by roboaaron1** [comment]
yes

**Comment by SebOuellette** [comment]
Okay well here's the thing. For one, you shouldn't be typing in that file anyways. Two, that is not an issue with this program in any way, it would be an issue with the editor you are using.
