### ISSUE TITLE
Reconnect/emoji bug

### ISSUE THREAD

**Issue by dcrime** [SebOuellette/Discord-LiveBot#30]
When the client reconnects (Either by putting the pc at sleep/hibernate or a connection loss) it duplicates the servers instead of refresing the servers
![Servers](https://user-images.githubusercontent.com/20734229/74349965-50e7a880-4db5-11ea-8a4c-1beb1067ecc1.PNG)
![Console](https://user-images.githubusercontent.com/20734229/74349974-534a0280-4db5-11ea-94ba-8f50d719c8e9.PNG)

Emoji bug in embeds
Discord
![Discord](https://user-images.githubusercontent.com/20734229/74354522-c9e9fe80-4dbb-11ea-83f0-019146572d6f.PNG)
Livebot (Also the green bar is missing)
![Livebot](https://user-images.githubusercontent.com/20734229/74354530-cbb3c200-4dbb-11ea-84b0-fa67e204646d.PNG)

**Comment by SebOuellette** [comment]
Hi!
Oh thanks I didn't even think about reconnecting. I'll fix that next commit. 
With the emoji bug, I'm aware of the issues, and have absolutely no idea what's causing it. The regex checks for a `:` `=` or `;` before it, and it cannot be a space. I'm having other issues with regexes in this project, like the link issue in #27. Normally I would just remove the specific regex for emoji, however I need a fix for this anyways so I'll be seeing what I can do.

**Comment by dcrime** [comment]
Every space is converted to a semicolon parseMessage.js line 6, removing that code seems to solve the issue, the emojis and embeds still work

**Comment by SebOuellette** [comment]
Oh right, I just need to change the order of emoji parsing and the html &nbsp; conversion

**Comment by SebOuellette** [comment]
Fixed in d601df97f26ddbea044650681a7251f1bf52dfb7

**Comment by SebOuellette** [comment]
Fixed in d601df97f26ddbea044650681a7251f1bf52dfb7

**Comment by SebOuellette** [comment]
Ok I believe it's fixed in 7dd0c50748ccd2cbc56f795799e19d41a64bd842. If it doesn't fix it for you feel free to re open this issue
