### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Rodzyne** [SebOuellette/Discord-LiveBot#33]
Every token I put is not working and they all should work correctly.

**Comment by dcrime** [comment]
What happens when you try to write a token? Does it just turn red? And in the console (ctrl + shift + i) what error do you get

**Comment by Rodzyne** [comment]
It turns red and maybe I'm blind or something because there is totally no error in console.

**Comment by dcrime** [comment]
Which branch and which os do you use?
If you're trying to log into a user account it might have quotes around it (ex "token") so make sure to remove them
Can you run a basic discord.js bot
Yeah, I've looked through the code and saw there's no logging for the code, it just makes the token box red, if you have the master branch try going in js->setToken.js and console log the catch statement

**Comment by SebOuellette** [comment]
How recent is this install for livebot?

**Comment by Rodzyne** [comment]
I'm using the newest version of livebot (branch Executable). My operating system is Windows. I'm sure that I deleted quotes from the token so they are not a problem.
The only tokens that are working for me are tokens of my bots. Any other token bot doesn't work even if it's correct.

**Comment by dcrime** [comment]
If SebOullette doesn't come up with anything can you try downloading the master branch and checking the error like I said earlier

**Comment by Rodzyne** [comment]
This is what it shows when I'm trying to run a bot with a correct token. I'm sure on 100% it's a valid token.
![Screenshot_34](https://user-images.githubusercontent.com/28383361/75112030-2eb91a80-5640-11ea-90c4-457e68ce2afb.png)

**Comment by dcrime** [comment]
From this error it seems it's trying to load the token from it's storage (which might not exist if you never logged in with a bot), it happens when the client starts tho my question is after it starts if you get an error aka when you write in the token and press "save"

**Comment by Rodzyne** [comment]
When I provide the token and click save, only the token box is changing to red. Nothing else happens. If you want I can record the whole operation of doing this and send you the recording.

**Comment by dcrime** [comment]
I see from your profile you know how to code, this project is open source so downloading the master branch allows you to change the earlier mentioned file, if you want to try solve it over discord and I can post here what was wrong later so the creator knows if there's a bug or not you can add me by this username daniel_crime#1551

**Comment by SebOuellette** [comment]
Huh.. I mean there's not much that can go wrong in this program... Could you try to remove this try-catch block in load.js and see what happens with the token then? https://images.soue.tk/wJtyfJl7ka.png

**Comment by SebOuellette** [comment]
And you're absolutely sure that the token is correct? Go to your [applications page](https://discordapp.com/developers/applications) and click the ["Copy" button](https://images.soue.tk/PdAED0Wbgj.png).

After that just paste your clipboard into the token bar in livebot, no need to alter it.

**Comment by dcrime** [comment]
The error persisted after logging the try catch ( setToken.js line 24 ), he got his token out of an app (my assumption is it's a bot maker since he did mention it before that)
I suggested for him to change the token and try it with a new one but he had to leave
I just got a message and true, it wasn't a problem with livebot, he changed the token and forgot about it

**Comment by SebOuellette** [comment]
Great! Thanks for letting me know
