### ISSUE TITLE
how do i run it?

### ISSUE THREAD

**Issue by DDOM-afk** [SebOuellette/Discord-LiveBot#34]

**Comment by dcrime** [comment]
https://github.com/SebOuellette/Discord-LiveBot#how-to-install

The manual way of downloading it
https://github.com/SebOuellette/Discord-LiveBot

The executable/easy way (Only for windows)
https://github.com/SebOuellette/Discord-LiveBot/tree/executable

**Comment by dcrime** [comment]
If the problem was resolved you can close the issue
