### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by LittlePotatoMan** [SebOuellette/Discord-LiveBot#43]
how do I access a human account as i would like to test this

**Comment by dcrime** [comment]
It's not really suggested to do so but if you really do want to do so then log in to your account on a web browser and find it in the local storage, I won't say more because I really don't suggest you doing so cause it's against the Discord TOS

**Comment by SebOuellette** [comment]
Since this is against tos (and I mean the answer has basically already been given by the wonderful dcrime) I'm going to close this issue. Feel free to make another if you need some help with something else!
