### ISSUE TITLE
dosent work

### ISSUE THREAD

**Issue by PatrickMSM-Chertes** [SebOuellette/Discord-LiveBot#44]
i put my token ad nothing

**Comment by dcrime** [comment]
Are you sure the token is correct? There was another person that changed their token and forgot about it so it didn't work for them

**Comment by SebOuellette** [comment]
Patrick can we have a checkup? Is it working for you now?

**Comment by SqueezyS** [comment]
It's not working for me either

**Comment by SebOuellette** [comment]
Squeezy what's not working for you? Same issue?

**Comment by SebOuellette** [comment]
The solution to this problem is using the correct token.
