### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by NitWitted** [SebOuellette/Discord-LiveBot#45]
It would be nice if we could click on links in livebot.

Maybe we could enter servers via links then.
Imagine the fun!

**Comment by dcrime** [comment]
Isn't that already a thing? Though in my fork I just made all the links open in your default browser since you can't really close these ones unless you close them from the taskbar

**Comment by NitWitted** [comment]
[https://drive.google.com/open?id=1nbuZm6NQaOgD9KYTz1Ptzfzdz7yExuIk](It's not working.)

**Comment by NitWitted** [comment]
[It's not working](https://drive.google.com/open?id=1nbuZm6NQaOgD9KYTz1Ptzfzdz7yExuIk)

**Comment by dcrime** [comment]
Try downloading my fork https://github.com/dcrime/Discord-LiveBot I don't have the executable branch tho since I don't know how to do it

**Comment by NitWitted** [comment]
how do i install it?

It only shows how for mac and linux.

**Comment by dcrime** [comment]
The installation is the same everywhere you need node.js and follow the instructions there, Node.js is required for npm
