### ISSUE TITLE
How do I run this on glitch.com?

### ISSUE THREAD

**Issue by Sup-Sup123** [SebOuellette/Discord-LiveBot#47]
Hello I was wondering if you could tell me how to use this code on glitch.com

**Comment by bobby365** [comment]
you don't host it you download it to your computer to use

**Comment by Sup-Sup123** [comment]
No you can run code using the website

**Comment by dcrime** [comment]
What do you plan on doing on the website? This program was made with electron so it opens a new browser so I'm unsure of what you're trying to achieve with this, it's specifically made to run on your pc

**Comment by Sup-Sup123** [comment]
The website allows you to run code

**Comment by SebOuellette** [comment]
Hi there. You cannot run this on glitch. Yes you can run code there, but not the electron app interface. It's not going to work
