### ISSUE TITLE
Error spam when there's no internet

### ISSUE THREAD

**Issue by dcrime** [SebOuellette/Discord-LiveBot#50]
![image](https://user-images.githubusercontent.com/20734229/82543714-47a86d80-9b54-11ea-82fa-74af397c54a2.png)

Could be fixed by having an error handler and just returning nothing

Also the scripts get loaded once again and since there's still no way of disabling them they may run twice (Happened on the first script I made where I was stupid enough to make a bug and realized I have to restart the client because of event listeners)

**Comment by SebOuellette** [comment]
There should be errors for the time being if there is no connection, that's what errors are for. The spash screen will fix this when it's added.
