### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by PhoneticDragon** [SebOuellette/Discord-LiveBot#53]
I'm On Linux and There Aren't Enough Instructions and I've Come From Windows Where Everything Is Just an Exe File You Don't Need These Insanely Long Manual Installs I am New To The Terminal and No one on youtube has a video to show me how

**Comment by SebOuellette** [comment]
Hi there! Just so you know, if you need help, you can ask on the discord server linked on a the readme for a faster response. 

Anyway, there are definitely enough instructions since the installation instructions on master are the same between windows and linux. What are you not able to do?

**Comment by PhoneticDragon** [comment]
I Don't know terminal and so I have the file but I type the command but It says "Command not found" and I don't know how to run it in administrator

**Comment by PhoneticDragon** [comment]
I Tried Looking On Youtube Because I didn't want to bother anyone

**Comment by SebOuellette** [comment]
Don't worry about bothering anybody, that's what we're here for! :D 
So, to get the command (and I forgot to put this in the readme originally, it's been updated now) you need to download [nodejs](https://nodejs.org/en/), then you can follow the rest of the steps in the readme, which I have written here:

 Use a terminal and navigate into that folder, using the command `cd` to change your directory. 
Once you're in the same folder as livebot, use `npm install` which will install everything it needs
Once npm install is done, use `npm test` which will start the program.

**Comment by PhoneticDragon** [comment]
Thanks
